name: MasterServer.CI
on:
  push:
    branches:
      - 'dev/pcclient'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Setup Nuget Package manager
      uses: nuget/setup-nuget@v1
    - name: Restore packages
      run: |
        cd BrowserClient
        nuget restore
    - name: Build solution
      run: |
        cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
        .\MSBuild.exe $Env:GITHUB_WORKSPACE\BrowserClient /p:Platform=x86 
    - name: Run tests 
      run: |
        cd BrowserClient\Deploy\Tests
        dotnet vstest BrowserClient.Test.WPFBrowserClient.dll