name: PythonConverter.CI

on:
  push:
    branches: 
      - PythonConverter

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Setup Nuget Package manager
      uses: nuget/setup-nuget@v1
    - name: Restore packages
      run: |
        cd PythonInterfaceConverter
        nuget restore
    - name: Build solution
      run: |
        cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
        .\MSBuild.exe $Env:GITHUB_WORKSPACE\PythonInterfaceConverter
    - name: Run tests 
      run: |
        cd CommunicationModule\Deploy\Tests
        dotnet test --no-build
